#开发配置文件
server :  
  #服务启动端口
  port :  8080
  #配置默认访问路径
  servlet:
    context-path: /bluewhale

spring:
  #thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    #prefix: /templates/
    suffix: .html
    #mode: HTML5
    #encoding: UTF-8
    #servlet:
      #content-type: text/html
    cache: false
    
  #邮件发送配置
  mail:
    #邮件服务地址
    host: smtp.163.com
    #端口
    port: 465
    protocol: smtp
    #编码格式
    default-encoding: UTF-8
    #邮箱地址
    username: bluewhalesoft@163.com
    #密码（授权码）
    password: bluewhale163
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
      mail:
        smtp:
          ssl:
            enable: true

#日志输出
logback:
  #日志输出使用的项目名称
  appname: BlueWhaleDev
  #日志输出文件路径
  logdir: /Users/curtin/Library/Log
 
 
 
#系统常量定义
bluewhale:
  #邮件地址
  mail:
    #发件人地址
    fromMail: bluewhalesoft@163.com

  #Excel文件上传下载地址
  #模块周报
  moduleWR:
    uploadPath: D:/BlueWhale/moduleWR/uploads
    downloadPath: D:/BlueWhale/moduleWR/downloads
#    uploadPath: /Users/curtin/bluewhale/moduleWR/uploads
#    downloadPath: /Users/curtin/bluewhale/moduleWR/downloads
  #客户周报
  customerWR:
    uploadPath: D:/BlueWhale/customerWR/uploads
    downloadPath: D:/BlueWhale/customerWR/downloads
#    uploadPath: /Users/curtin/bluewhale/customerWR/uploads
#    downloadPath: /Users/curtin/bluewhale/customerWR/downloads
  #项目周报
  projectWR:
    uploadPath: D:/BlueWhale/projectWR/uploads
    downloadPath: D:/BlueWhale/projectWR/downloads
#    uploadPath: /Users/curtin/bluewhale/projectWR/uploads
#    downloadPath: /Users/curtin/bluewhale/projectWR/downloads